### ISSUE TITLE
add zbase32 support

### ISSUE THREAD

**Issue by toxeus** [andreasots/base32#26]
I would like to contribute [zbase32](https://philzimmermann.com/docs/human-oriented-base-32-encoding.txt) support. Would the project accept such a contribution?

**Comment by andreasots** [comment]
I believe z-base-32 has already been implemented in #25  (commit 145447d06f307610cee2b2381b48606506d1b88e) which has been published on crates.io as v0.5.0.

**Comment by toxeus** [comment]
Thank you! Works as intended :+1:
