### ISSUE TITLE
Library no longer exports an RFC4648 in the Alphabet

### ISSUE THREAD

**Issue by tkennedy1-godaddy** [andreasots/base32#27]
The newly merged https://github.com/andreasots/base32/pull/25 breaks anyone who was using `RFC4648` as all uppercase because it removes the variant from the list.

**Comment by andreasots** [comment]
This is intentional. [Rust API guidelines](https://rust-lang.github.io/api-guidelines/naming.html) state that in `UpperCamelCase` names such as enum variants acronyms count as a single "word" and as such are lowercased: `Uuid` instead of `UUID` and thus `Rfc4648` instead of `RFC4648`.

**Comment by dhuseby** [comment]
This is why my original PR bumped the minor version number to signal the breaking change.
