### ISSUE TITLE
DECODE -> ENCODE same value returns different

### ISSUE THREAD

**Issue by mmacedoeu** [andreasots/base32#7]
This test fail:

#[test]
fn testdecodeencode() {
    let input = "05CMPBRN3GNARRPBFRPVGWS8R5";
    let vec = base32::decode(Alphabet::Crockford, input).unwrap();
    let output = base32::encode(Alphabet::Crockford, &vec);
    assert!(input == output);
}

**Comment by andreasots** [comment]
I believe that this is not a bug as both of `05CMPBRN3GNARRPBFRPVGWS8R5` (the value of `input`) and `05CMPBRN3GNARRPBFRPVGWS8R4` (the value of `output`) decode to the same value. I've also checked against Python 3.5.2's `base64` module and it has the same behaviour.

**Comment by mmacedoeu** [comment]
The problem is data truncation at the end. 26 chars long input uses 26 * 5 = 130 bits = 16.25 and you are truncating it to 16 bytes and losing data, when encoding back data is the representation of the truncated data and not the original one.

**Comment by Veetaha** [comment]
@andreasots this looks like a serious issue to me. The documentation doesn't mention anything about the lossy conversion. This also probably makes this implementation of Crockford's base32 not compatible with the one in `rusty_ulid` crate I guess?
